### ISSUE TITLE
DemoVerity这种拖拽验证如何和服务器结合起来?

### ISSUE THREAD

**Issue by badboy-tian** [longer96/flutter-demo#1]
这种本地的校验方式作用好像不大呢, 如何结合服务器呢? 难道服务器把正确答案发送给客户端, 客户端自己验证就行了吗? 那岂不是很好作弊呢? 谢谢

**Comment by longer96** [comment]
你好  验证放在前端确实是掩耳盗铃。demo只是实现了操作功能。
如果需要真正是达到验证的效果，需要采集拖动的轨迹坐标，将N个坐标信息打包给后端。
后端通过算法来做人机验证，就可以得到验证结果。
